version: '3'

services:
  node-red:
    image: nodered/node-red:latest
    container_name: rvc-node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    environment:
      - TZ=America/New_York
    networks:
      - rvc-network

networks:
  rvc-network:
    external: true
