# Configure Home Assistant
homeassistant:
  name: RVC Home Assistant
  unit_system: imperial
  time_zone: America/New_York

# Configure MQTT properly
mqtt:
  broker: 100.110.189.122
  port: 9001
  username: rc
  password: rc
  client_id: home_assistant
  protocol: websockets
  discovery: true

# Include the lights configuration
light: !include lights.yaml

# Configure logging
logger:
  default: info
  logs:
    homeassistant.components.mqtt: debug

# Configure history
history:

# Configure custom recorder settings
recorder:
  purge_keep_days: 30

# Enable the frontend
frontend:

# Enable configuration UI
config:

# Default dependencies
http:

# Enable automation
automation:
