homeassistant:
  name: RVC Home Assistant
  unit_system: imperial
  time_zone: America/New_York

# Enable MQTT integration
mqtt: ~

# Include the lights configuration
light: !include lights.yaml
sensor: !include mqtt_sensors.yaml

# Configure logging
logger:
  default: info
  logs:
    homeassistant.components.mqtt: debug

# Configure history
history:

# Configure custom recorder settings
recorder:
  purge_keep_days: 30

# Enable the frontend
frontend:

# Enable configuration UI
config:

# Default dependencies
http:

# Enable automation
automation:
