homeassistant:
  name: RVC Home Assistant
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customizations.yaml

# Configure MQTT with the correct broker details
mqtt:
  # Used for UI configuration


# RVC MQTT custom component for sensors and climate controls
rvc_mqtt:
  # Load the main sensor configuration
  sensor: !include custom_components/rvc_mqtt/rvc_sensors.yaml
  # Load the thermostat sensors configuration
  thermostat_sensor: !include custom_components/rvc_mqtt/thermostat_sensors.yaml
  # Load the climate controls configuration
  climate: !include custom_components/rvc_mqtt/climate.yaml
  # Load the thermostat climate controls configuration
  thermostat_climate: !include custom_components/rvc_mqtt/thermostat_climate.yaml

# Additional MQTT device configuration can be done through the UI
# Configuration > Devices & Services > MQTT > Configure

# Configure logging
logger:
  default: info
  logs:
    homeassistant.components.mqtt: debug
    custom_components.rvc_lights: debug
    custom_components.rvc_mqtt: debug
    custom_components.rvc_mqtt.climate: debug

# Configure history
history:

# Configure custom recorder settings
recorder:
  purge_keep_days: 30

# Enable RVC Lights component with auto-discovery disabled
rvc_lights:
  enable_auto_discovery: true

# RVC Lights customizations are included in the homeassistant section at the top

# Enable the frontend
frontend:
  # Note: themes directory may need to be created
  # themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js
  
# Dashboards
lovelace:
  mode: yaml
  dashboards:
    rv-thermostats:  # Changed to include a hyphen as required
      mode: yaml
      title: RV Thermostats
      icon: mdi:thermometer
      show_in_sidebar: true
      filename: rvc_thermostats_dashboard.yaml

# Enable configuration UI
config:

# Load the thermostat helper entities configuration
input_number: !include_dir_merge_named custom_components/rvc_mqtt/input_number
input_select: !include_dir_merge_named custom_components/rvc_mqtt/input_select

# Default dependencies
http:

# Enable automation
automation:

# Enable shell commands for direct control of RVC lights
# Disabled in favor of the rvc_lights custom component
# shell_command: !include shell_commands.yaml
